language: ruby
rvm:
 - "2.4.1"
cache: bundler
before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:drop db:create db:migrate
script: 
  - RAILS_ENV=test bundle exec rake assets:precompile
  - RAILS_ENV=test bundle exec rake rspec spec 
